### ISSUE TITLE
为什么无法备份

### ISSUE THREAD

**Issue by ysq5202121** [zhp8341/flink-streaming-platform-web#105]
![image](https://github.com/zhp8341/flink-streaming-platform-web/assets/8586973/dc8396b4-54d7-4be9-b574-d84e7053f311)
![image](https://github.com/zhp8341/flink-streaming-platform-web/assets/8586973/9d7541c0-9d39-49ed-857a-fe94a32b7b71)
可以进行checkopoint

**Comment by ysq5202121** [comment]
2023-07-23 15:31:41,053 INFO  org.apache.flink.runtime.security.modules.JaasModule         [] - Jaas file will be created as /tmp/jaas-2759765809329062664.conf.
2023-07-23 15:31:41,064 INFO  org.apache.flink.client.cli.CliFrontend                      [] - Running 'savepoint' command.
2023-07-23 15:31:41,069 ERROR org.apache.flink.client.cli.CliFrontend                      [] - Fatal error while running command line interface.
java.lang.NoSuchMethodError: org.apache.commons.cli.CommandLine.hasOption(Lorg/apache/commons/cli/Option;)Z
	at org.apache.flink.client.cli.SavepointOptions.<init>(SavepointOptions.java:45) ~[flink-dist-1.16.0.jar:1.16.0]
	at org.apache.flink.client.cli.CliFrontend.savepoint(CliFrontend.java:728) ~[flink-dist-1.16.0.jar:1.16.0]
	at org.apache.flink.client.cli.CliFrontend.parseAndRun(CliFrontend.java:1108) ~[flink-dist-1.16.0.jar:1.16.0]
	at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:1168) ~[flink-dist-1.16.0.jar:1.16.0]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_302]
	at javax.security.auth.Subject.doAs(Subject.java:422) ~[?:1.8.0_302]
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1754) ~[flink-shaded-hadoop-2-uber-2.7.5-10.0.jar:2.7.5-10.0]
	at org.apache.flink.runtime.security.contexts.HadoopSecurityContext.runSecured(HadoopSecurityContext.java:41) ~[flink-dist-1.16.0.jar:1.16.0]
	at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1168) [flink-dist-1.16.0.jar:1.16.0]

**Comment by ysq5202121** [comment]
缺少commons-cli
https://repo1.maven.org/maven2/commons-cli/commons-cli/1.5.0/
已解决
