### ISSUE TITLE
执行sql后从flink日志发现这个错误

### ISSUE THREAD

**Issue by kongweiteng** [zhp8341/flink-streaming-platform-web#30]
![image](https://user-images.githubusercontent.com/28074873/111280268-95a7d800-8676-11eb-838c-1773ab9b10cb.png)

**Comment by kongweiteng** [comment]
2021-03-16 16:23:56,614 INFO  com.flink.streaming.core.execute.Executes                    [] - #############ddl############# 
 CREATE TABLE orders (
    order_id INT
) WITH (
    'connector' = 'mysql-cdc',
    'hostname' = 'localhost',
    'port' = '3306',
    'username' = 'root',
    'password' = 'qazxswedc1234',
    'database-name' = 'flink_web',
    'table-name' = 'orders'
)
2021-03-16 16:23:56,689 INFO  com.flink.streaming.core.execute.Executes                    [] - #############ddl############# 
 CREATE TABLE orders1 (
    order_id INT
) WITH (
    'connector' = 'jdbc',
    'hostname' = 'localhost',
    'port' = '3306',
    'username' = 'root',
    'password' = 'qazxswedc1234',
    'driver' = 'com.mysql.cj.jdbc.Driver',
    'database-name' = 'flink_web',
    'table-name' = 'orders1'
)
2021-03-16 16:23:56,693 ERROR com.flink.streaming.core.JobApplication                      [] - 任务执行失败：
java.lang.IllegalStateException: No operators defined in streaming topology. Cannot generate StreamGraph.
	at org.apache.flink.table.planner.utils.ExecutorUtils.generateStreamGraph(ExecutorUtils.java:41) ~[flink-table-blink_2.11-1.12.2.jar:1.12.2]
	at org.apache.flink.table.planner.delegation.StreamExecutor.createPipeline(StreamExecutor.java:50) ~[flink-table-blink_2.11-1.12.2.jar:1.12.2]
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeInternal(TableEnvironmentImpl.java:679) ~[flink-table-blink_2.11-1.12.2.jar:1.12.2]
	at org.apache.flink.table.api.internal.StatementSetImpl.execute(StatementSetImpl.java:98) ~[flink-table-blink_2.11-1.12.2.jar:1.12.2]
	at com.flink.streaming.core.execute.Executes.callDml(Executes.java:67) ~[flink-streaming-core-1.2.0.RELEASE.jar:1.2.0.RELEASE]
	at com.flink.streaming.core.JobApplication.main(JobApplication.java:87) ~[flink-streaming-core-1.2.0.RELEASE.jar:1.2.0.RELEASE]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:349) ~[flink-dist_2.11-1.12.2.jar:1.12.2]
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:219) ~[flink-dist_2.11-1.12.2.jar:1.12.2]
	at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114) ~[flink-dist_2.11-1.12.2.jar:1.12.2]
	at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:812) ~[flink-dist_2.11-1.12.2.jar:1.12.2]
	at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:246) ~[flink-dist_2.11-1.12.2.jar:1.12.2]
	at org.apache.flink.client.cli.CliFrontend.parseAndRun(CliFrontend.java:1054) ~[flink-dist_2.11-1.12.2.jar:1.12.2]
	at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:1132) ~[flink-dist_2.11-1.12.2.jar:1.12.2]
	at org.apache.flink.runtime.security.contexts.NoOpSecurityContext.runSecured(NoOpSecurityContext.java:28) [flink-dist_2.11-1.12.2.jar:1.12.2]
	at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1132) [flink-dist_2.11-1.12.2.jar:1.12.2]

**Comment by zhp8341** [comment]
必须要有insert 语句

**Comment by kongweiteng** [comment]
解决了，最终是发现insert语句忘了写分号，一顿好找
