### ISSUE TITLE
任务提交失败，实际执行成功

### ISSUE THREAD

**Issue by fzyejy** [zhp8341/flink-streaming-platform-web#55]
flink版本 1.12.0，local方式启动。
通过sql方式提交简单的任务，通过查看日志发现，开始都执行正常，执行到最后一步的时候，出现任务失败，但实际任务已经成功执行，日志显示的也很奇怪（如下），已经得到jobID，却说这个jobID已被自己提交，然后失败？烦请大神解答一下
PS：10次可能有1次成功
 #############INSERT_INTO############# 
insert into test_01 select * from test

[job-submitted-success] 解析得到的appId是:Job has been submitted with JobID 31efc43cc3d1f185cb9887e405b53588
31efc43cc3d1f185cb9887e405b53588
Job has been submitted with JobID 31efc43cc3d1f185cb9887e405b53588
job-submitted-success:31efc43cc3d1f185cb9887e405b53588

rs=0

 任务失败 appId=Job has been submitted with JobID 31efc43cc3d1f185cb9887e405b53588
31efc43cc3d1f185cb9887e405b53588BizException(code=501, errorMsg=任务失败)

（重要）请登陆服务器分别查看下面两个目录下的错误日志192.168.3.158
web系统日志目录（web日志）：/data/flink-streaming-platform-web/logs/error.log
flink提交日志目录（flink客户端日志：/data/flink-1.12.0/log/)

启动结束时间: 2021-07-05 10:22:40
######启动结果是 失败############################## 

## /data/flink-streaming-platform-web/logs/error.log

com.flink.streaming.web.exceptions.BizException: 任务失败
        at com.flink.streaming.web.ao.impl.JobBaseServiceAOImpl$1.submitJobForStandalone(JobBaseServiceAOImpl.java:321)
        at com.flink.streaming.web.ao.impl.JobBaseServiceAOImpl$1.run(JobBaseServiceAOImpl.java:196)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2021-07-05 10:22:40.550 [pool-2-thread-3] ERROR com.flink.streaming.web.rpc.impl.FlinkRestRpcAdapterImpl - [FlinkRestRpcAdapterImpl - getJobInfoForStandaloneByAppId] json 异常 res=null
org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request: [{"errors":["org.apache.flink.runtime.rest.handler.RestHandlerException: Bad request, could not parse parameters: Cannot resolve path parameter (jobid) from value \"Job has been submitted with JobID 31... (6388 bytes)]
        at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:101)
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:184)
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:125)
        at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:782)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:740)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:674)
        at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:315)
        at com.flink.streaming.web.rpc.impl.FlinkRestRpcAdapterImpl.getJobInfoForStandaloneByAppId(FlinkRestRpcAdapterImpl.java:44)
        at com.flink.streaming.web.ao.impl.JobBaseServiceAOImpl$1.submitJobForStandalone(JobBaseServiceAOImpl.java:315)
        at com.flink.streaming.web.ao.impl.JobBaseServiceAOImpl$1.run(JobBaseServiceAOImpl.java:196)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2021-07-05 10:22:40.550 [pool-2-thread-3] ERROR com.flink.streaming.web.ao.impl.JobBaseServiceAOImpl - [JobBaseServiceAOImpl - submitJobForStandalone] [submitJobForStandalone] is error jobStandaloneInfo=JobStandaloneInfo(jid=null, state=null, errors=400 Bad Request: [{"errors":["org.apache.flink.runtime.rest.handler.RestHandlerException: Bad request, could not parse parameters: Cannot resolve path parameter (jobid) from value \"Job has been submitted with JobID 31... (6388 bytes)])
2021-07-05 10:22:40.550 [pool-2-thread-3] ERROR com.flink.streaming.web.ao.impl.JobBaseServiceAOImpl - [JobBaseServiceAOImpl - run] exe is error
com.flink.streaming.web.exceptions.BizException: 任务失败
        at com.flink.streaming.web.ao.impl.JobBaseServiceAOImpl$1.submitJobForStandalone(JobBaseServiceAOImpl.java:321)
        at com.flink.streaming.web.ao.impl.JobBaseServiceAOImpl$1.run(JobBaseServiceAOImpl.java:196)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by gaozhenfeng1** [comment]
请问解决了吗？我这边跟你一模一样

**Comment by tanqiong** [comment]
我也遇到了，我修改了类com.flink.streaming.web.rpc.impl.CommandRpcClinetAdapterImpl 关于appId解析的clearInfoLogStream方法解决

**Comment by daixiaoyu** [comment]
如果用流式 任务 当批处理，执行完成后会显示失败。我现在暂时还没遇到这个问题，批处理任务，我这边执行完成后，是显示的提交完成

**Comment by zhp8341** [comment]
job解析bug已经修复
